logging:
  console:
    level: info

scheduler:
  defaults:
    interval: 60
  maxconcurrency: 16

tasks:
  defaults:
    timeout: 5000
  maxconcurrency: 48
  queuesize: 96
  maxpending: 256
  repository:
    bucketscount: 16

stats:
  bucketscount: 32

endpoints:
  http:
    bind: :8080
  metrics:
    bind: :8081
